export const TEXT = {
    CONTACT: 'Contact',
    ADDRESS: 'Address:',
    CONTACT_CITY: 'Gurugram',
    EMAIL: 'Email:',
    EMAIL_ADDRESS: 'raikwar.manjari@gmail.com',
    PHONE: 'Phone:',
    LOGIN: 'Login',
    SIGNUP: "Signup",
    LOGOUT:  'Logout',
    ALREADY_HAVE_AN_ACCOUNT: 'Already have an account? ',
    DONT_HAVE_AN_ACCOUNT: "Don't have an account?",
    CREATE: 'Create',
    SUBMIT: 'Submit',
  };